Return-Path: mansouri@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:31:44 +0000 (UTC)
Received: from [10.233.100.153] (mail [10.233.100.153])
	by mail.petromaz.ir (Postfix) with ESMTPSA id 5176910181B
	for <kolahi@petromaz.ir>; Mon, 27 Jan 2025 14:31:44 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============2423821210417322742=="
MIME-Version: 1.0
From: mansouri@petromaz.ir
To: kolahi@petromaz.ir
Subject: =?utf-8?b?2YHYp9uM2YQg2Kfaqdiz2YQ=?=
Message-Id: <20250127143144.5176910181B@mail.petromaz.ir>
Date: Mon, 27 Jan 2025 14:31:44 +0000 (UTC)

--===============2423821210417322742==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUK2YHYp9uM2YQg2Kfaqdiz2YTbjCDaqdmHINmE2KfYstmFINiv2KfYtNiq24zYryDY
sdinINit2K/Yp9qp2KvYsSDYqtinINmB2LHYr9inINin2LIg2LfYsduM2YIg2K/bjNiq2KfYr9uM
2YjYryDYqNix2KfbjNiq2KfZhiDYp9ix2LPYp9mEINmF24zigIzaqdmG2YUuCg==

--===============2423821210417322742==--
