Return-Path: mansouri@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:07:38 +0000 (UTC)
Received: from [10.233.107.174] (mail [10.233.107.174])
	by mail.petromaz.ir (Postfix) with ESMTPSA id 99C2022088F
	for <kolahi@petromaz.ir>; Sun, 19 Jan 2025 15:07:38 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============1302831771100836732=="
MIME-Version: 1.0
From: mansouri@petromaz.ir
To: kolahi@petromaz.ir
Subject: =?utf-8?b?2YHYp9uM2YQg2Kfaqdiz2YQ=?=
Message-Id: <20250119150738.99C2022088F@mail.petromaz.ir>
Date: Sun, 19 Jan 2025 15:07:38 +0000 (UTC)

--===============1302831771100836732==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUK2YHYp9uM2YQg2Kfaqdiz2YTbjCDaqdmHINmE2KfYstmFINiv2KfYtNiq24zYryDY
sdinINit2K/Yp9qp2KvYsSDYqtinINmB2LHYr9inINin2LIg2LfYsduM2YIg2K/bjNiq2KfYr9uM
2YjYryDYqNix2KfbjNiq2KfZhiDYp9ix2LPYp9mEINmF24zigIzaqdmG2YUuCg==

--===============1302831771100836732==--
