Return-Path: moradi@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:07:38 +0000 (UTC)
Received: from [10.233.107.174] (mail [10.233.107.174])
	by mail.petromaz.ir (Postfix) with ESMTPSA id 8CDE22208E0
	for <savad-koohi@petromaz.ir>; Sun, 19 Jan 2025 15:07:38 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============4259780372128628395=="
MIME-Version: 1.0
From: moradi@petromaz.ir
To: savad-koohi@petromaz.ir
Subject: software
Message-Id: <20250119150738.8CDE22208E0@mail.petromaz.ir>
Date: Sun, 19 Jan 2025 15:07:38 +0000 (UTC)

--===============4259780372128628395==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUK2YbYsdmFINin2YHYstin2LEg2K/Ysdiu2YjYp9iz2Kog2LTYr9mHINix2Kcg2b7b
jNmI2LPYqiDaqdix2K/ZhS4K

--===============4259780372128628395==
Content-Type: application/octet-stream; Name="email3/kerio_connect"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="email3/kerio_connect"

IyEvYmluL2Jhc2gKCnVzZXJuYW1lPSIiCnBhc3N3b3JkPSIiIAoKc2VydmVyX2lwPSQoaXAgciB8
IGdyZXAgZGVmYXVsdCB8IGN1dCAtZiAzIC1kICcgJykKc2VydmVyX2lwPSIiCmNhc2UgIiQxIiBp
bgpsb2dvdXQpCgljdXJsIC0taW5zZWN1cmUgLVggR0VUIGh0dHBzOi8vJHNlcnZlcl9pcDo0MDgx
L2ludGVybmFsL2xvZ291dAoJOzsKKikKCglpZiBbIC16ICR1c2VybmFtZSBdOyB0aGVuCgkJcmVh
ZCAtcCAiRW50ZXIgdGhlIFVzZXJuYW1lOiIgdXNlcm5hbWUKCWZpCgoJIyBpZiBwYXNzd29yZCBp
cyBlbXB0eSBnZXQgaXQhCglpZiBbIC16ICRwYXNzd29yZCBdOyB0aGVuCgkJcmVhZCAtc3AgIlBh
c3N3b3JkOiIgcGFzc3dvcmQKCWZpCgoJY3VybCAtLWluc2VjdXJlIC1YIFBPU1QgaHR0cHM6Ly8k
c2VydmVyX2lwOjQwODEvaW50ZXJuYWwvZG9sb2dpbi5waHA/TlRMTT0wIC0tZGF0YS11cmxlbmNv
ZGUgImtlcmlvX3VzZXJuYW1lPSR1c2VybmFtZSIgLS1kYXRhLXVybGVuY29kZSAia2VyaW9fcGFz
c3dvcmQ9JHBhc3N3b3JkIgoKCXJlcz0kKGN1cmwgLUkgaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbSAt
bSA1IDI+L2Rldi9udWxsIHwgaGVhZCAtbiAxIHwgY3V0IC1mIDIgLWQgIiAiKQoJaWYgW1sgJHJl
cyA9PSAiMjAwIiBdXTsgdGhlbgoJCXByaW50ZiAiXDAzM1sxbVwwMzNbOTJtWW91IEFyZSBDb25u
ZWN0ZWQgTm93IVwwMzNbMG0iCgllbHNlCgkJcHJpbnRmICJcMDMzWzFtXDAzM1s5MW1Ob3QgQ29u
bmVjdGVkIVwwMzNbMG0iCglmaQoJcHJpbnRmICJcblxuIgplc2FjCg==

--===============4259780372128628395==--
