Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 19:47:46 +0000 (UTC)
Received: from mail.petromaz.ir (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 3D9A3220439
	for <spam.zju1yzg0yz@petromaz.ir>; Sun, 19 Jan 2025 19:47:46 +0000 (UTC)
To: spam.zju1yzg0yz@petromaz.ir
Message-ID: <1754830346.19.1737316065990.JavaMail.zimbra@mail>
Subject: zimbra-spam-report: admin@petromaz.ir: spam
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_18_1609857613.1737316065977"
X-Zimbra-Spam-Report-Sender: admin@petromaz.ir
X-Zimbra-Spam-Report-Type: spam
X-Originating-IP: [192.168.48.63]
Date: Sun, 19 Jan 2025 19:47:46 +0000 (UTC)
From: MAILER-DAEMON

------=_Part_18_1609857613.1737316065977
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Content-Description: Zimbra spam classification report

Classified-By: admin@petromaz.ir
Classified-As: spam
Action: move
Source-Folder: /Conversations
Destination-Folder: /Junk
Destination-Mailbox: 

------=_Part_18_1609857613.1737316065977
Content-Type: message/rfc822
Content-Disposition: attachment

Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:06:04 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 017626004E6
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:34 +0000 (UTC)
X-Spam-Flag: NO
X-Spam-Score: -0.999
X-Spam-Level:
X-Spam-Status: No, score=-0.999 required=6.6 tests=[ALL_TRUSTED=-1,
	URIBL_BLOCKED=0.001] autolearn=unavailable autolearn_force=no
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10032)
	with ESMTP id gCoQmcNm2wK4 for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 0E1CB6004E0
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
X-Virus-Scanned: amavisd-new at petromaz.ir
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id pYME1V2sLtvo for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:32 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id DBD3A6004E4
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:32 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service service started on mail.petromaz.ir
Message-Id: <20241230204432.DBD3A6004E4@mail.petromaz.ir>
Date: Mon, 30 Dec 2024 20:44:32 +0000 (UTC)

Dec 30 20:44:31 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir service changed from stopped to running

------=_Part_18_1609857613.1737316065977--
