Return-Path: rezaee@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:07:38 +0000 (UTC)
Received: from [10.233.107.174] (mail [10.233.107.174])
	by mail.petromaz.ir (Postfix) with ESMTPSA id 816512208DE
	for <mansouri@petromaz.ir>; Sun, 19 Jan 2025 15:07:38 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============5630279120638050834=="
MIME-Version: 1.0
From: rezaee@petromaz.ir
To: mansouri@petromaz.ir
Subject: =?utf-8?b?2K/Ysdiu2YjYp9iz2Kog2K/Ys9iq2LHYs9uMINio2Ycg2LPYsdmI2LE=?=
Message-Id: <20250119150738.816512208DE@mail.petromaz.ir>
Date: Sun, 19 Jan 2025 15:07:38 +0000 (UTC)

--===============5630279120638050834==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUK2YTYt9mB2Kcg2qnZhNuM2K8g2LnZhdmI2YXbjCDZhdix2Kcg2K/YsSDYs9ix2YjY
sSDYp9i22KfZgdmHINqp2YbbjNivINiq2Kcg2KjYqtmI2KfZhtmFINio2K/ZiNmGINm+2LPZiNix
2K8g2KjZhyDYotmGINmI2LXZhCDYtNmI2YUuCgpzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUVB
WE5RdE9kYjF5N08rN2VnT2tOaGZMMzd5VURESituTG5ZQm4wQ1drSVMwcEkvQjNrYVgrVWxNZWJi
VzZCRVd2cHFsTVh1VmhNTUVPRndUS0ROcE5vUXlhOGVnd1ptMXdMVkd5akI0NkZ0S0NiNDFxYXg3
VEVFcStEdzkveEdhS1dDSGlpN2xUTnl0NmZvZkI0dnAwRlhvMGpaeEdzdEdwM3ZtYmlyWG9IbkdT
aE13MFJSUEE2Q2lpMmxhcUJHbUZ5SWxGYmw5aU1Ea1pPQTJRK3JsMHlFUnFlYUlLOTBlcENsdXdV
eTB0eVlxRGxmeEF5c0RCd2hraGhCOWZTcjIrSUU5eDZaS2EyZVJrWTQ0UlhZTHZFcENFWlVKNWtW
MWM1WGkrVi8zblVzY1BxMmdUWHQrKzh1SUxvUjIzUG41NWdtMlJKRmo4M2Q4NDZyY1Q2R0F1dmJR
QUFBUUJmb1hrZitNeTkvTWFkcEJyOTlaRC9yZTR5VlczNmpsK1JmR3BTY0JSb01YNU5PWTNNSHJh
MjRzY29WaFpkUDR4Y0V0SHprbUx3NEVhb1dRWWNRTmJRS0g5elpwSHpwUTJtQ3c0Ukx6QkpydmFm
KzhVSVlrT0xabmRsSktuUVZkSVJyWWpUSG9Nc1FHZzd6TXJVSWRqdE1BQ21oUmxKN0Ztd3hQYjJ4
ZDhtV2tzcnQ4aDZoSTBtMVZsazhzVGdOa3BVY0hEeFlteTVwcExHRHYwUWxKNlZSbmNObWx2QTJF
N21EZS84TE52eTFzY0thdERDblpzTWtmZHRkcjJpTkM5QS8zdGNKeGdjTllQNTlwaTJFTFZhTDUx
WE1FcHk1RFBLQXJuaWtmdEMrR1doTzJHc2ZmS0ZvKzZYUTRZZlRvbU15QWR3aklUTW5OdVJvbC9s
WGpmLwo=

--===============5630279120638050834==--
