Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:25:17 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id E934060046C
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:43:26 +0000 (UTC)
X-Spam-Flag: NO
X-Spam-Score: -0.999
X-Spam-Level:
X-Spam-Status: No, score=-0.999 required=6.6 tests=[ALL_TRUSTED=-1,
	URIBL_BLOCKED=0.001] autolearn=unavailable autolearn_force=no
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10032)
	with ESMTP id 4wYDOM5yj7l0 for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:43:26 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 1B789600474
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:43:26 +0000 (UTC)
X-Virus-Scanned: amavisd-new at petromaz.ir
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id NVELVwR4K5l9 for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:43:26 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id EC4DF60046A
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:43:25 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service service stopped on mail.petromaz.ir
Message-Id: <20241230204325.EC4DF60046A@mail.petromaz.ir>
Date: Mon, 30 Dec 2024 20:43:25 +0000 (UTC)

Dec 30 20:43:25 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir service changed from running to stopped
