Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:26:54 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 017626004E6
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:34 +0000 (UTC)
X-Spam-Flag: NO
X-Spam-Score: -0.999
X-Spam-Level:
X-Spam-Status: No, score=-0.999 required=6.6 tests=[ALL_TRUSTED=-1,
	URIBL_BLOCKED=0.001] autolearn=unavailable autolearn_force=no
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10032)
	with ESMTP id gCoQmcNm2wK4 for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 0E1CB6004E0
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
X-Virus-Scanned: amavisd-new at petromaz.ir
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id pYME1V2sLtvo for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:32 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id DBD3A6004E4
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:32 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service service started on mail.petromaz.ir
Message-Id: <20241230204432.DBD3A6004E4@mail.petromaz.ir>
Date: Mon, 30 Dec 2024 20:44:32 +0000 (UTC)

Dec 30 20:44:31 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir service changed from stopped to running
