Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:06:04 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id BFC75600466
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:43:26 +0000 (UTC)
X-Spam-Flag: NO
X-Spam-Score: -0.999
X-Spam-Level:
X-Spam-Status: No, score=-0.999 required=6.6 tests=[ALL_TRUSTED=-1,
	URIBL_BLOCKED=0.001] autolearn=unavailable autolearn_force=no
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10032)
	with ESMTP id 4WnaPb_w7Xr9 for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:43:26 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id F0A6360046C
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:43:25 +0000 (UTC)
X-Virus-Scanned: amavisd-new at petromaz.ir
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id GH4dx1p2Zkd2 for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:43:25 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id B8771600462
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:43:25 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service mailboxd stopped on mail.petromaz.ir
Message-Id: <20241230204325.B8771600462@mail.petromaz.ir>
Date: Mon, 30 Dec 2024 20:43:25 +0000 (UTC)

Dec 30 20:43:25 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir mailboxd changed from running to stopped
