Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:06:04 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 37F8F6004F5
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:34 +0000 (UTC)
X-Spam-Flag: NO
X-Spam-Score: -0.999
X-Spam-Level:
X-Spam-Status: No, score=-0.999 required=6.6 tests=[ALL_TRUSTED=-1,
	URIBL_BLOCKED=0.001] autolearn=ham autolearn_force=no
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10032)
	with ESMTP id uGbvRsqZUX8X for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 7FBAA6004EB
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
X-Virus-Scanned: amavisd-new at petromaz.ir
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id K-k3nORHDuuC for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 476756004E4
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service zimbraAdmin started on mail.petromaz.ir
Message-Id: <20241230204433.476756004E4@mail.petromaz.ir>
Date: Mon, 30 Dec 2024 20:44:33 +0000 (UTC)

Dec 30 20:44:32 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir zimbraAdmin changed from stopped to running
