Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:26:55 +0000 (UTC)
Received: by mail.petromaz.ir (Postfix)
	id 310BC102E07; Mon, 27 Jan 2025 14:26:53 +0000 (UTC)
Date: Mon, 27 Jan 2025 14:26:53 +0000 (UTC)
From: MAILER-DAEMON@mail.petromaz.ir (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: admin@petromaz.ir
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="760781E8280.1737988013/mail.petromaz.ir"
Content-Transfer-Encoding: 7bit
Message-Id: <20250127142654.310BC102E07@mail.petromaz.ir>

This is a MIME-encapsulated message.

--760781E8280.1737988013/mail.petromaz.ir
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host mail.petromaz.ir.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<admin@petromaz.ir>: host mail.petromaz.ir[127.0.0.1] said: 451 4.0.0 Temporary
    message delivery failure try again (in reply to end of DATA command)

--760781E8280.1737988013/mail.petromaz.ir
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; mail.petromaz.ir
X-Postfix-Queue-ID: 760781E8280
X-Postfix-Sender: rfc822; admin@petromaz.ir
Arrival-Date: Mon, 30 Dec 2024 20:44:34 +0000 (UTC)

Final-Recipient: rfc822; admin@petromaz.ir
Original-Recipient: rfc822;admin@petromaz.ir
Action: failed
Status: 4.0.0
Remote-MTA: dns; mail.petromaz.ir
Diagnostic-Code: smtp; 451 4.0.0 Temporary message delivery failure try again

--760781E8280.1737988013/mail.petromaz.ir
Content-Description: Undelivered Message
Content-Type: message/rfc822

Return-Path: <admin@petromaz.ir>
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 760786004E0
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:34 +0000 (UTC)
X-Spam-Flag: NO
X-Spam-Score: -0.999
X-Spam-Level:
X-Spam-Status: No, score=-0.999 required=6.6 tests=[ALL_TRUSTED=-1,
	URIBL_BLOCKED=0.001] autolearn=ham autolearn_force=no
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10032)
	with ESMTP id dOCcQ8eju5RC for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
Received: from localhost (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id B30A66004EF
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
X-Virus-Scanned: amavisd-new at petromaz.ir
Received: from mail.petromaz.ir ([127.0.0.1])
	by localhost (mail.petromaz.ir [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id iJVsXv6kH83s for <admin@petromaz.ir>;
	Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 86D206004EC
	for <admin@petromaz.ir>; Mon, 30 Dec 2024 20:44:33 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service zimlet started on mail.petromaz.ir
Message-Id: <20241230204433.86D206004EC@mail.petromaz.ir>
Date: Mon, 30 Dec 2024 20:44:33 +0000 (UTC)

Dec 30 20:44:33 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir zimlet changed from stopped to running

--760781E8280.1737988013/mail.petromaz.ir--
