Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:06:04 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id E95F3220866
	for <admin@petromaz.ir>; Sun, 19 Jan 2025 15:06:02 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service mailboxd started on mail.petromaz.ir
Message-Id: <20250119150602.E95F3220866@mail.petromaz.ir>
Date: Sun, 19 Jan 2025 15:06:02 +0000 (UTC)

Dec 30 20:44:31 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir mailboxd changed from stopped to running
