Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:30:58 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 6C5F81010ED
	for <admin@petromaz.ir>; Mon, 27 Jan 2025 14:30:52 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service mailbox stopped on mail.petromaz.ir
Message-Id: <20250127143052.6C5F81010ED@mail.petromaz.ir>
Date: Mon, 27 Jan 2025 14:30:52 +0000 (UTC)

Dec 30 20:43:25 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir mailbox changed from running to stopped
