Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Sun, 19 Jan 2025 15:07:23 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id E0BFC2208B8
	for <admin@petromaz.ir>; Sun, 19 Jan 2025 15:07:22 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service zimlet started on mail.petromaz.ir
Message-Id: <20250119150722.E0BFC2208B8@mail.petromaz.ir>
Date: Sun, 19 Jan 2025 15:07:22 +0000 (UTC)

Dec 30 20:44:33 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir zimlet changed from stopped to running
