Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:31:02 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 084411016E0
	for <admin@petromaz.ir>; Mon, 27 Jan 2025 14:30:54 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service zimbra started on mail.petromaz.ir
Message-Id: <20250127143054.084411016E0@mail.petromaz.ir>
Date: Mon, 27 Jan 2025 14:30:54 +0000 (UTC)

Dec 30 20:44:32 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir zimbra changed from stopped to running
