Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:31:02 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id C0FCF1016B9
	for <admin@petromaz.ir>; Mon, 27 Jan 2025 14:30:53 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service mailboxd started on mail.petromaz.ir
Message-Id: <20250127143053.C0FCF1016B9@mail.petromaz.ir>
Date: Mon, 27 Jan 2025 14:30:53 +0000 (UTC)

Dec 30 20:44:31 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir mailboxd changed from stopped to running
