Return-Path: admin@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:31:02 +0000 (UTC)
Received: from localhost.localdomain (localhost [127.0.0.1])
	by mail.petromaz.ir (Postfix) with ESMTP id 5BB331016EC
	for <admin@petromaz.ir>; Mon, 27 Jan 2025 14:30:54 +0000 (UTC)
To: admin@petromaz.ir
From: admin@petromaz.ir
Subject: Service zimlet started on mail.petromaz.ir
Message-Id: <20250127143054.5BB331016EC@mail.petromaz.ir>
Date: Mon, 27 Jan 2025 14:30:54 +0000 (UTC)

Dec 30 20:44:33 localhost zmconfigd[13831]: Service status change: mail.petromaz.ir zimlet changed from stopped to running
