Return-Path: rezaee@petromaz.ir
Received: from localhost (LHLO mail.petromaz.ir) (127.0.0.1) by
 mail.petromaz.ir with LMTP; Mon, 27 Jan 2025 14:31:44 +0000 (UTC)
Received: from [10.233.100.153] (mail [10.233.100.153])
	by mail.petromaz.ir (Postfix) with ESMTPSA id D14F2102A2B
	for <pirouz@petromaz.ir>; Mon, 27 Jan 2025 14:31:44 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============3779550118454562254=="
MIME-Version: 1.0
From: rezaee@petromaz.ir
To: pirouz@petromaz.ir
Subject: =?utf-8?b?2YHYp9uM2YQg2b7Yp9uM2KrZiNmGINin2LPaqdin2K/Ypw==?=
Message-Id: <20250127143144.D14F2102A2B@mail.petromaz.ir>
Date: Mon, 27 Jan 2025 14:31:44 +0000 (UTC)

--===============3779550118454562254==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

2LPZhNin2YUg2KjZhyDZhti42LEg2YXbjNix2LPZhyDaqdivINin2LPaqdin2K/YpyDbjNmHINio
2Kfar9uMINiv2KfYsdmH2Iwg2YTYt9mB2Kcg2YHYp9uM2YQg2b7Yp9uM2KrZiNmG2LQg2LHYpyDb
jNmHINio2LHYsdiz24wg2KjaqdmG

--===============3779550118454562254==
Content-Type: application/octet-stream; Name="email6/scada-source.zip"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="email6/scada-source.zip"

UEsDBBQACAAIAEGzZlgAAAAAAAAAANkCAAAGACAAYXBwLnB5VVQNAAdDvOhlQtboZTzW6GV1eAsA
AQToAwAABOgDAACVUslqwzAQvesrhE4WpA4JFELApadeW2hvIQjVHjkmtuSOZRwa8u8deUu6XOqT
PPPmLSMZdBXvAI+f0OZxi2XDi6p26DmdlSlOzAREAymCn3veHcGqgNYGBoQpdXOc+k/hZ8ERPlpo
fDjYDFB5qOpSewiFrEBIqdXLOGRM1zVPhslIKasrUEoyxh6pEaNrPURiKSTLwPCC6E6R3DJOHxlr
0f7UiEQPig++KsWCA6LDZDQUa8ybOAcfib4u5C8hCx1NVeAPLmuSnXh5fn0T+0GdVhEERvnUWQ/W
k/eJneJUA/vYIyZBzgO6MFwoQQHmOYecct1UBtpvyYZlReOuxmhzKvGuMzVJyVmnBBuNVckf+P1q
/X/m0tlcXVMQZXJLO4qFy6L8RjRe+yJdnse3M+F229V6s5eXu/O3hxNt5GW4n56lK/yBu5roAx+t
rBOS64abq20Td1jQ6id99leWMC3ZF1BLBwg+ZEwNYQEAANkCAABQSwECFAMUAAgACABBs2ZYPmRM
DWEBAADZAgAABgAgAAAAAAAAAAAA/YEAAAAAYXBwLnB5VVQNAAdDvOhlQtboZTzW6GV1eAsAAQTo
AwAABOgDAABQSwUGAAAAAAEAAQBUAAAAtQEAAAAA

--===============3779550118454562254==--
